### PR TITLE
Fixed theme index in fullscreen mode

### LINKED ISSUE #1039: MRT_TablePaper zIndex is lower than Appbar in Fullscreen
### material-react-table version

2.12.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

The zIndex for MRT_TablePaper was adjusted from 9999 to 999 in commit [3b5cad3](https://github.com/KevinVandy/material-react-table/commit/3b5cad3ffd9a424ac17be1d88f8a78f56bb65c4b#diff-00a3e2014eb5ffa2f936fedb1389421d5ab0dd2cfe43d2bb391ccd4bceb03359). However, this alteration causes the table to appear beneath the AppBar component in full screen mode.

Ideally, MRT_TablePaper should inherit its zIndex from the theme, specifically theme.zIndex.modal.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-morytr?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

_No response_

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### PR DESCRIPTION
**Pull request by helt**
Fixes https://github.com/KevinVandy/material-react-table/issues/1039

@KevinVandy Is using the theme here okay?

### CODE REVIEW

**Comment by KevinVandy** [comment]
Do tooltips still work?

**Comment by helt** [comment]
If you mean the tooltips for e.g. the sorting button, then yes. In normal view and also in fullscreen

image

File: packages/material-react-table/src/components/table/MRT_TablePaper.tsx [hunk 1]
```diff
@@ -58,7 +61,7 @@ export const MRT_TablePaper = <TData extends MRT_RowData>({
               right: 0,
               top: 0,
               width: '100dvw',
-              zIndex: 999,
+              zIndex: theme.zIndex.modal + 1,
```
Comment (sadik-malik) [inline packages/material-react-table/src/components/table/MRT_TablePaper.tsx:64]: @helt, please don't add "+1" to theme.zIndex.modal. This will cause, other modal and dialog components to appear below MRT_TablePaper

Comment (helt) [reply packages/material-react-table/src/components/table/MRT_TablePaper.tsx:64]: @sadik-malik Whats your suggestion to use then? Plain `theme.zIndex.modal` ?

Comment (sadik-malik) [reply packages/material-react-table/src/components/table/MRT_TablePaper.tsx:64]: yes, if it is not breaking any of the test cases.

Comment (sadik-malik) [reply packages/material-react-table/src/components/table/MRT_TablePaper.tsx:64]: https://stackblitz.com/edit/github-morytr-zqdrka?file=src%2Fexample.tsx

@helt, In the above stackblitz example you can see Dialog component is appearing below MRT_TablePaper when zIndex is set to `theme.zIndex.modal + 1`

Comment (sadik-malik) [reply packages/material-react-table/src/components/table/MRT_TablePaper.tsx:64]: @helt any update

Comment (KevinVandy) [reply packages/material-react-table/src/components/table/MRT_TablePaper.tsx:64]: so this should work perfectly fine as long as no `+ 1` is added?

**Review by KevinVandy — APPROVED** [review]
will remove +1
